services:
  postgres:
    image: postgres:16
    container_name: hci-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Phong416ct5x2
      POSTGRES_DB: hci_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: